//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMad.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Etiqueta
    {
        public Etiqueta()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public long tagID { get; set; }
        public string nombre { get; set; }
        public Nullable<int> numUsos { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): TagCom
        /// </summary>
        public virtual ICollection<Comentario> Comentario { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (nombre == null ? 0 : nombre.GetHashCode());
    			hash = hash * multiplier + (numUsos == null ? 0 : numUsos.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Etiqueta target = obj as Etiqueta;
    
    		return true
               &&  (this.tagID == target.tagID )       
               &&  (this.nombre == target.nombre )       
               &&  (this.numUsos == target.numUsos )       
               ;
    
        }
    
    
    	public static bool operator ==(Etiqueta  objA, Etiqueta  objB)
        {
            // Check if the objets are the same Etiqueta entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Etiqueta  objA, Etiqueta  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strEtiqueta = new StringBuilder();
    
    		strEtiqueta.Append("[ ");
           strEtiqueta.Append(" tagID = " + tagID + " | " );       
           strEtiqueta.Append(" nombre = " + nombre + " | " );       
           strEtiqueta.Append(" numUsos = " + numUsos + " | " );       
            strEtiqueta.Append("] ");    
    
    		return strEtiqueta.ToString();
        }
    
    
    }
}
