//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMad.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Valoracion = new HashSet<Valoracion>();
        }
    
        public long productID { get; set; }
        public string nombre { get; set; }
        public string categoria { get; set; }
        public System.DateTime date { get; set; }
        public long vendedor { get; set; }
        public byte[] imagen { get; set; }
        public string descripcion { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ComentarioProducto
        /// </summary>
        public virtual ICollection<Comentario> Comentario { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ProductoVendedor
        /// </summary>
        public virtual Usuario Usuario { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ValoracionProducto
        /// </summary>
        public virtual ICollection<Valoracion> Valoracion { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (nombre == null ? 0 : nombre.GetHashCode());
    			hash = hash * multiplier + (categoria == null ? 0 : categoria.GetHashCode());
    			hash = hash * multiplier + date.GetHashCode();
    			hash = hash * multiplier + vendedor.GetHashCode();
    			hash = hash * multiplier + (imagen == null ? 0 : imagen.GetHashCode());
    			hash = hash * multiplier + (descripcion == null ? 0 : descripcion.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Producto target = obj as Producto;
    
    		return true
               &&  (this.productID == target.productID )       
               &&  (this.nombre == target.nombre )       
               &&  (this.categoria == target.categoria )       
               &&  (this.date == target.date )       
               &&  (this.vendedor == target.vendedor )       
               &&  (this.imagen == target.imagen )       
               &&  (this.descripcion == target.descripcion )       
               ;
    
        }
    
    
    	public static bool operator ==(Producto  objA, Producto  objB)
        {
            // Check if the objets are the same Producto entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Producto  objA, Producto  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strProducto = new StringBuilder();
    
    		strProducto.Append("[ ");
           strProducto.Append(" productID = " + productID + " | " );       
           strProducto.Append(" nombre = " + nombre + " | " );       
           strProducto.Append(" categoria = " + categoria + " | " );       
           strProducto.Append(" date = " + date + " | " );       
           strProducto.Append(" vendedor = " + vendedor + " | " );       
           strProducto.Append(" imagen = " + imagen + " | " );       
           strProducto.Append(" descripcion = " + descripcion + " | " );       
            strProducto.Append("] ");    
    
    		return strProducto.ToString();
        }
    
    
    }
}
