//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMad.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Producto = new HashSet<Producto>();
            this.Valoracion = new HashSet<Valoracion>();
        }
    
        public long userID { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string idioma { get; set; }
        public string nacionalidad { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ComentarioUsuario
        /// </summary>
        public virtual ICollection<Comentario> Comentario { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ProductoVendedor
        /// </summary>
        public virtual ICollection<Producto> Producto { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_PuntuacionUsuario
        /// </summary>
        public virtual Puntuacion Puntuacion { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ValoracionComprador
        /// </summary>
        public virtual ICollection<Valoracion> Valoracion { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (username == null ? 0 : username.GetHashCode());
    			hash = hash * multiplier + (pwd == null ? 0 : pwd.GetHashCode());
    			hash = hash * multiplier + (nombre == null ? 0 : nombre.GetHashCode());
    			hash = hash * multiplier + (apellidos == null ? 0 : apellidos.GetHashCode());
    			hash = hash * multiplier + (email == null ? 0 : email.GetHashCode());
    			hash = hash * multiplier + (idioma == null ? 0 : idioma.GetHashCode());
    			hash = hash * multiplier + (nacionalidad == null ? 0 : nacionalidad.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Usuario target = obj as Usuario;
    
    		return true
               &&  (this.userID == target.userID )       
               &&  (this.username == target.username )       
               &&  (this.pwd == target.pwd )       
               &&  (this.nombre == target.nombre )       
               &&  (this.apellidos == target.apellidos )       
               &&  (this.email == target.email )       
               &&  (this.idioma == target.idioma )       
               &&  (this.nacionalidad == target.nacionalidad )       
               ;
    
        }
    
    
    	public static bool operator ==(Usuario  objA, Usuario  objB)
        {
            // Check if the objets are the same Usuario entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Usuario  objA, Usuario  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strUsuario = new StringBuilder();
    
    		strUsuario.Append("[ ");
           strUsuario.Append(" userID = " + userID + " | " );       
           strUsuario.Append(" username = " + username + " | " );       
           strUsuario.Append(" pwd = " + pwd + " | " );       
           strUsuario.Append(" nombre = " + nombre + " | " );       
           strUsuario.Append(" apellidos = " + apellidos + " | " );       
           strUsuario.Append(" email = " + email + " | " );       
           strUsuario.Append(" idioma = " + idioma + " | " );       
           strUsuario.Append(" nacionalidad = " + nacionalidad + " | " );       
            strUsuario.Append("] ");    
    
    		return strUsuario.ToString();
        }
    
    
    }
}
