//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMad.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Valoracion
    {
        public long valID { get; set; }
        public long comprador { get; set; }
        public long producto { get; set; }
        public double puntuacion { get; set; }
        public string comentario { get; set; }
        public System.DateTime date { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ValoracionProducto
        /// </summary>
        public virtual Producto Producto1 { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ValoracionComprador
        /// </summary>
        public virtual Usuario Usuario { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + comprador.GetHashCode();
    			hash = hash * multiplier + producto.GetHashCode();
    			hash = hash * multiplier + puntuacion.GetHashCode();
    			hash = hash * multiplier + (comentario == null ? 0 : comentario.GetHashCode());
    			hash = hash * multiplier + date.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Valoracion target = obj as Valoracion;
    
    		return true
               &&  (this.valID == target.valID )       
               &&  (this.comprador == target.comprador )       
               &&  (this.producto == target.producto )       
               &&  (this.puntuacion == target.puntuacion )       
               &&  (this.comentario == target.comentario )       
               &&  (this.date == target.date )       
               ;
    
        }
    
    
    	public static bool operator ==(Valoracion  objA, Valoracion  objB)
        {
            // Check if the objets are the same Valoracion entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Valoracion  objA, Valoracion  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strValoracion = new StringBuilder();
    
    		strValoracion.Append("[ ");
           strValoracion.Append(" valID = " + valID + " | " );       
           strValoracion.Append(" comprador = " + comprador + " | " );       
           strValoracion.Append(" producto = " + producto + " | " );       
           strValoracion.Append(" puntuacion = " + puntuacion + " | " );       
           strValoracion.Append(" comentario = " + comentario + " | " );       
           strValoracion.Append(" date = " + date + " | " );       
            strValoracion.Append("] ");    
    
    		return strValoracion.ToString();
        }
    
    
    }
}
